# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import tunnel_pb2 as tunnel__pb2


class ExtensionTunnelStub(object):
    """ExtensionTunnel maintains the reverse bidirectional HTTP-over-gRPC tunnel.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/tunnel.ExtensionTunnel/Connect',
                request_serializer=tunnel__pb2.TunnelMessage.SerializeToString,
                response_deserializer=tunnel__pb2.TunnelMessage.FromString,
                )


class ExtensionTunnelServicer(object):
    """ExtensionTunnel maintains the reverse bidirectional HTTP-over-gRPC tunnel.
    """

    def Connect(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExtensionTunnelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=tunnel__pb2.TunnelMessage.FromString,
                    response_serializer=tunnel__pb2.TunnelMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tunnel.ExtensionTunnel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ExtensionTunnel(object):
    """ExtensionTunnel maintains the reverse bidirectional HTTP-over-gRPC tunnel.
    """

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/tunnel.ExtensionTunnel/Connect',
            tunnel__pb2.TunnelMessage.SerializeToString,
            tunnel__pb2.TunnelMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class DatabaseServiceStub(object):
    """DatabaseService is the Core-Managed Document Store (CMDS) proxy.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.unary_unary(
                '/tunnel.DatabaseService/Put',
                request_serializer=tunnel__pb2.PutRequest.SerializeToString,
                response_deserializer=tunnel__pb2.PutResponse.FromString,
                )
        self.Get = channel.unary_unary(
                '/tunnel.DatabaseService/Get',
                request_serializer=tunnel__pb2.GetRequest.SerializeToString,
                response_deserializer=tunnel__pb2.GetResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/tunnel.DatabaseService/Delete',
                request_serializer=tunnel__pb2.DeleteRequest.SerializeToString,
                response_deserializer=tunnel__pb2.DeleteResponse.FromString,
                )
        self.Find = channel.unary_unary(
                '/tunnel.DatabaseService/Find',
                request_serializer=tunnel__pb2.FindRequest.SerializeToString,
                response_deserializer=tunnel__pb2.FindResponse.FromString,
                )


class DatabaseServiceServicer(object):
    """DatabaseService is the Core-Managed Document Store (CMDS) proxy.
    """

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Find(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DatabaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=tunnel__pb2.PutRequest.FromString,
                    response_serializer=tunnel__pb2.PutResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=tunnel__pb2.GetRequest.FromString,
                    response_serializer=tunnel__pb2.GetResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=tunnel__pb2.DeleteRequest.FromString,
                    response_serializer=tunnel__pb2.DeleteResponse.SerializeToString,
            ),
            'Find': grpc.unary_unary_rpc_method_handler(
                    servicer.Find,
                    request_deserializer=tunnel__pb2.FindRequest.FromString,
                    response_serializer=tunnel__pb2.FindResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tunnel.DatabaseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DatabaseService(object):
    """DatabaseService is the Core-Managed Document Store (CMDS) proxy.
    """

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tunnel.DatabaseService/Put',
            tunnel__pb2.PutRequest.SerializeToString,
            tunnel__pb2.PutResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tunnel.DatabaseService/Get',
            tunnel__pb2.GetRequest.SerializeToString,
            tunnel__pb2.GetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tunnel.DatabaseService/Delete',
            tunnel__pb2.DeleteRequest.SerializeToString,
            tunnel__pb2.DeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Find(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tunnel.DatabaseService/Find',
            tunnel__pb2.FindRequest.SerializeToString,
            tunnel__pb2.FindResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class EventBusServiceStub(object):
    """EventBusService is the distributed event bus over gRPC.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Publish = channel.unary_unary(
                '/tunnel.EventBusService/Publish',
                request_serializer=tunnel__pb2.PublishRequest.SerializeToString,
                response_deserializer=tunnel__pb2.PublishResponse.FromString,
                )
        self.Subscribe = channel.stream_stream(
                '/tunnel.EventBusService/Subscribe',
                request_serializer=tunnel__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=tunnel__pb2.EventMessage.FromString,
                )


class EventBusServiceServicer(object):
    """EventBusService is the distributed event bus over gRPC.
    """

    def Publish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventBusServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=tunnel__pb2.PublishRequest.FromString,
                    response_serializer=tunnel__pb2.PublishResponse.SerializeToString,
            ),
            'Subscribe': grpc.stream_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=tunnel__pb2.SubscribeRequest.FromString,
                    response_serializer=tunnel__pb2.EventMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tunnel.EventBusService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EventBusService(object):
    """EventBusService is the distributed event bus over gRPC.
    """

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tunnel.EventBusService/Publish',
            tunnel__pb2.PublishRequest.SerializeToString,
            tunnel__pb2.PublishResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/tunnel.EventBusService/Subscribe',
            tunnel__pb2.SubscribeRequest.SerializeToString,
            tunnel__pb2.EventMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class FileServiceStub(object):
    """FileService exposes file token generation / metadata to extensions.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateDownloadToken = channel.unary_unary(
                '/tunnel.FileService/GenerateDownloadToken',
                request_serializer=tunnel__pb2.TokenRequest.SerializeToString,
                response_deserializer=tunnel__pb2.TokenResponse.FromString,
                )
        self.GetMetadata = channel.unary_unary(
                '/tunnel.FileService/GetMetadata',
                request_serializer=tunnel__pb2.FileMetaRequest.SerializeToString,
                response_deserializer=tunnel__pb2.FileMetaResponse.FromString,
                )


class FileServiceServicer(object):
    """FileService exposes file token generation / metadata to extensions.
    """

    def GenerateDownloadToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateDownloadToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateDownloadToken,
                    request_deserializer=tunnel__pb2.TokenRequest.FromString,
                    response_serializer=tunnel__pb2.TokenResponse.SerializeToString,
            ),
            'GetMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetadata,
                    request_deserializer=tunnel__pb2.FileMetaRequest.FromString,
                    response_serializer=tunnel__pb2.FileMetaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tunnel.FileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileService(object):
    """FileService exposes file token generation / metadata to extensions.
    """

    @staticmethod
    def GenerateDownloadToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tunnel.FileService/GenerateDownloadToken',
            tunnel__pb2.TokenRequest.SerializeToString,
            tunnel__pb2.TokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tunnel.FileService/GetMetadata',
            tunnel__pb2.FileMetaRequest.SerializeToString,
            tunnel__pb2.FileMetaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
