// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"
)

type AuditLog struct {
	ID           int32        `json:"id"`
	UserID       string       `json:"user_id"`
	Action       string       `json:"action"`
	ExtensionKey string       `json:"extension_key"`
	HttpPath     string       `json:"http_path"`
	ClientIp     string       `json:"client_ip"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

type FileDownloadToken struct {
	Token     string    `json:"token"`
	FileID    string    `json:"file_id"`
	UserID    string    `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

type PluginQueue struct {
	ID            int64          `json:"id"`
	OwnerKey      string         `json:"owner_key"`
	Topic         string         `json:"topic"`
	Payload       []byte         `json:"payload"`
	Status        string         `json:"status"`
	Priority      int32          `json:"priority"`
	Attempts      int32          `json:"attempts"`
	MaxAttempts   int32          `json:"max_attempts"`
	AvailableAt   time.Time      `json:"available_at"`
	LockedUntil   sql.NullTime   `json:"locked_until"`
	DedupKey      sql.NullString `json:"dedup_key"`
	LastError     sql.NullString `json:"last_error"`
	ParentTraceID sql.NullString `json:"parent_trace_id"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type SystemFile struct {
	ID             string         `json:"id"`
	Filename       string         `json:"filename"`
	Size           int64          `json:"size"`
	MimeType       string         `json:"mime_type"`
	StorageKey     string         `json:"storage_key"`
	UploaderID     string         `json:"uploader_id"`
	Status         sql.NullString `json:"status"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	OwnerPluginKey string         `json:"owner_plugin_key"`
}

type SystemUser struct {
	ID           int32        `json:"id"`
	Username     string       `json:"username"`
	PasswordHash string       `json:"password_hash"`
	Role         string       `json:"role"`
	CreatedAt    sql.NullTime `json:"created_at"`
}
