// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
)

type ExtensionVersion struct {
	ExtensionKey string       `json:"extension_key"`
	Version      string       `json:"version"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type SystemUser struct {
	ID           int32        `json:"id"`
	Username     string       `json:"username"`
	PasswordHash string       `json:"password_hash"`
	Role         string       `json:"role"`
	CreatedAt    sql.NullTime `json:"created_at"`
}
