// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"
)

type AuditLog struct {
	ID           int32        `json:"id"`
	UserID       string       `json:"user_id"`
	Action       string       `json:"action"`
	ExtensionKey string       `json:"extension_key"`
	HttpPath     string       `json:"http_path"`
	ClientIp     string       `json:"client_ip"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

type Extension struct {
	Key         string       `json:"key"`
	DisplayName string       `json:"display_name"`
	Version     string       `json:"version"`
	MenuIcon    string       `json:"menu_icon"`
	MenuPath    string       `json:"menu_path"`
	Status      string       `json:"status"`
	CreatedAt   sql.NullTime `json:"created_at"`
	ApprovedAt  sql.NullTime `json:"approved_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type ExtensionSecret struct {
	ID           int64        `json:"id"`
	ExtensionKey string       `json:"extension_key"`
	SecretHash   string       `json:"secret_hash"`
	Label        string       `json:"label"`
	CreatedAt    sql.NullTime `json:"created_at"`
	LastUsedAt   sql.NullTime `json:"last_used_at"`
	RevokedAt    sql.NullTime `json:"revoked_at"`
}

type ExtensionVersion struct {
	ExtensionKey string       `json:"extension_key"`
	Version      string       `json:"version"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type FileDownloadToken struct {
	Token     string    `json:"token"`
	FileID    string    `json:"file_id"`
	UserID    string    `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

type SystemFile struct {
	ID         string         `json:"id"`
	Filename   string         `json:"filename"`
	Size       int64          `json:"size"`
	MimeType   string         `json:"mime_type"`
	StorageKey string         `json:"storage_key"`
	UploaderID string         `json:"uploader_id"`
	Status     sql.NullString `json:"status"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

type SystemUser struct {
	ID           int32        `json:"id"`
	Username     string       `json:"username"`
	PasswordHash string       `json:"password_hash"`
	Role         string       `json:"role"`
	CreatedAt    sql.NullTime `json:"created_at"`
}
