// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package sqlc

import (
	"context"
)

const getExtensionVersion = `-- name: GetExtensionVersion :one
SELECT version FROM extension_versions WHERE extension_key = $1
`

func (q *Queries) GetExtensionVersion(ctx context.Context, extensionKey string) (string, error) {
	row := q.db.QueryRowContext(ctx, getExtensionVersion, extensionKey)
	var version string
	err := row.Scan(&version)
	return version, err
}

const updateExtensionVersion = `-- name: UpdateExtensionVersion :exec
INSERT INTO extension_versions (extension_key, version, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (extension_key)
DO UPDATE SET version = EXCLUDED.version, updated_at = NOW()
`

type UpdateExtensionVersionParams struct {
	ExtensionKey string `json:"extension_key"`
	Version      string `json:"version"`
}

func (q *Queries) UpdateExtensionVersion(ctx context.Context, arg UpdateExtensionVersionParams) error {
	_, err := q.db.ExecContext(ctx, updateExtensionVersion, arg.ExtensionKey, arg.Version)
	return err
}
