// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countAdmins = `-- name: CountAdmins :one
SELECT COUNT(*) FROM system_users WHERE role = 'admin'
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM system_users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExtensionSecret = `-- name: CreateExtensionSecret :one
INSERT INTO extension_secrets (extension_key, secret_hash, label)
VALUES ($1, $2, $3)
RETURNING id, extension_key, secret_hash, label, created_at, last_used_at, revoked_at
`

type CreateExtensionSecretParams struct {
	ExtensionKey string `json:"extension_key"`
	SecretHash   string `json:"secret_hash"`
	Label        string `json:"label"`
}

func (q *Queries) CreateExtensionSecret(ctx context.Context, arg CreateExtensionSecretParams) (ExtensionSecret, error) {
	row := q.db.QueryRowContext(ctx, createExtensionSecret, arg.ExtensionKey, arg.SecretHash, arg.Label)
	var i ExtensionSecret
	err := row.Scan(
		&i.ID,
		&i.ExtensionKey,
		&i.SecretHash,
		&i.Label,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO system_users (username, password_hash, role) VALUES ($1, $2, $3)
`

type CreateUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.Username, arg.PasswordHash, arg.Role)
	return err
}

const deleteExtension = `-- name: DeleteExtension :exec
DELETE FROM extensions WHERE key = $1
`

func (q *Queries) DeleteExtension(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteExtension, key)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM system_users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getExtension = `-- name: GetExtension :one
SELECT key, display_name, version, menu_icon, menu_path, status, created_at, approved_at, updated_at FROM extensions WHERE key = $1
`

func (q *Queries) GetExtension(ctx context.Context, key string) (Extension, error) {
	row := q.db.QueryRowContext(ctx, getExtension, key)
	var i Extension
	err := row.Scan(
		&i.Key,
		&i.DisplayName,
		&i.Version,
		&i.MenuIcon,
		&i.MenuPath,
		&i.Status,
		&i.CreatedAt,
		&i.ApprovedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExtensionVersion = `-- name: GetExtensionVersion :one
SELECT version FROM extension_versions WHERE extension_key = $1
`

func (q *Queries) GetExtensionVersion(ctx context.Context, extensionKey string) (string, error) {
	row := q.db.QueryRowContext(ctx, getExtensionVersion, extensionKey)
	var version string
	err := row.Scan(&version)
	return version, err
}

const getFile = `-- name: GetFile :one
SELECT id, filename, size, mime_type, storage_key, uploader_id, status, created_at FROM system_files WHERE id = $1
`

func (q *Queries) GetFile(ctx context.Context, id string) (SystemFile, error) {
	row := q.db.QueryRowContext(ctx, getFile, id)
	var i SystemFile
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Size,
		&i.MimeType,
		&i.StorageKey,
		&i.UploaderID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, role, created_at FROM system_users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (SystemUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i SystemUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, role FROM system_users WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID           int32  `json:"id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (user_id, action, extension_key, http_path, client_ip)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAuditLogParams struct {
	UserID       string `json:"user_id"`
	Action       string `json:"action"`
	ExtensionKey string `json:"extension_key"`
	HttpPath     string `json:"http_path"`
	ClientIp     string `json:"client_ip"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.UserID,
		arg.Action,
		arg.ExtensionKey,
		arg.HttpPath,
		arg.ClientIp,
	)
	return err
}

const insertDownloadToken = `-- name: InsertDownloadToken :exec
INSERT INTO file_download_tokens (token, file_id, user_id, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertDownloadTokenParams struct {
	Token     string    `json:"token"`
	FileID    string    `json:"file_id"`
	UserID    string    `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) InsertDownloadToken(ctx context.Context, arg InsertDownloadTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertDownloadToken,
		arg.Token,
		arg.FileID,
		arg.UserID,
		arg.ExpiresAt,
	)
	return err
}

const insertFile = `-- name: InsertFile :exec
INSERT INTO system_files (id, filename, size, mime_type, storage_key, uploader_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertFileParams struct {
	ID         string `json:"id"`
	Filename   string `json:"filename"`
	Size       int64  `json:"size"`
	MimeType   string `json:"mime_type"`
	StorageKey string `json:"storage_key"`
	UploaderID string `json:"uploader_id"`
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) error {
	_, err := q.db.ExecContext(ctx, insertFile,
		arg.ID,
		arg.Filename,
		arg.Size,
		arg.MimeType,
		arg.StorageKey,
		arg.UploaderID,
	)
	return err
}

const listActiveExtensionSecrets = `-- name: ListActiveExtensionSecrets :many
SELECT id, extension_key, secret_hash, label, created_at, last_used_at, revoked_at FROM extension_secrets
WHERE extension_key = $1 AND revoked_at IS NULL
ORDER BY id
`

func (q *Queries) ListActiveExtensionSecrets(ctx context.Context, extensionKey string) ([]ExtensionSecret, error) {
	rows, err := q.db.QueryContext(ctx, listActiveExtensionSecrets, extensionKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExtensionSecret
	for rows.Next() {
		var i ExtensionSecret
		if err := rows.Scan(
			&i.ID,
			&i.ExtensionKey,
			&i.SecretHash,
			&i.Label,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, user_id, action, extension_key, http_path, client_ip, created_at FROM audit_logs ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ExtensionKey,
			&i.HttpPath,
			&i.ClientIp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExtensionSecrets = `-- name: ListExtensionSecrets :many
SELECT id, extension_key, secret_hash, label, created_at, last_used_at, revoked_at FROM extension_secrets
WHERE extension_key = $1
ORDER BY id
`

func (q *Queries) ListExtensionSecrets(ctx context.Context, extensionKey string) ([]ExtensionSecret, error) {
	rows, err := q.db.QueryContext(ctx, listExtensionSecrets, extensionKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExtensionSecret
	for rows.Next() {
		var i ExtensionSecret
		if err := rows.Scan(
			&i.ID,
			&i.ExtensionKey,
			&i.SecretHash,
			&i.Label,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExtensions = `-- name: ListExtensions :many
SELECT key, display_name, version, menu_icon, menu_path, status, created_at, approved_at, updated_at FROM extensions ORDER BY created_at DESC
`

func (q *Queries) ListExtensions(ctx context.Context) ([]Extension, error) {
	rows, err := q.db.QueryContext(ctx, listExtensions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Extension
	for rows.Next() {
		var i Extension
		if err := rows.Scan(
			&i.Key,
			&i.DisplayName,
			&i.Version,
			&i.MenuIcon,
			&i.MenuPath,
			&i.Status,
			&i.CreatedAt,
			&i.ApprovedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, role, created_at FROM system_users ORDER BY id
`

type ListUsersRow struct {
	ID        int32        `json:"id"`
	Username  string       `json:"username"`
	Role      string       `json:"role"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeExtensionSecret = `-- name: RevokeExtensionSecret :exec
UPDATE extension_secrets SET revoked_at = NOW() WHERE id = $1 AND extension_key = $2
`

type RevokeExtensionSecretParams struct {
	ID           int64  `json:"id"`
	ExtensionKey string `json:"extension_key"`
}

func (q *Queries) RevokeExtensionSecret(ctx context.Context, arg RevokeExtensionSecretParams) error {
	_, err := q.db.ExecContext(ctx, revokeExtensionSecret, arg.ID, arg.ExtensionKey)
	return err
}

const setExtensionStatus = `-- name: SetExtensionStatus :exec
UPDATE extensions
SET status = $1::text,
    approved_at = CASE WHEN $1::text = 'approved' THEN NOW() ELSE approved_at END,
    updated_at = NOW()
WHERE key = $2
`

type SetExtensionStatusParams struct {
	Status string `json:"status"`
	Key    string `json:"key"`
}

func (q *Queries) SetExtensionStatus(ctx context.Context, arg SetExtensionStatusParams) error {
	_, err := q.db.ExecContext(ctx, setExtensionStatus, arg.Status, arg.Key)
	return err
}

const touchExtensionSecret = `-- name: TouchExtensionSecret :exec
UPDATE extension_secrets SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) TouchExtensionSecret(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchExtensionSecret, id)
	return err
}

const updateExtensionVersion = `-- name: UpdateExtensionVersion :exec
INSERT INTO extension_versions (extension_key, version, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (extension_key)
DO UPDATE SET version = EXCLUDED.version, updated_at = NOW()
`

type UpdateExtensionVersionParams struct {
	ExtensionKey string `json:"extension_key"`
	Version      string `json:"version"`
}

func (q *Queries) UpdateExtensionVersion(ctx context.Context, arg UpdateExtensionVersionParams) error {
	_, err := q.db.ExecContext(ctx, updateExtensionVersion, arg.ExtensionKey, arg.Version)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE system_users SET password_hash = $2 WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           int32  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE system_users SET role = $2 WHERE id = $1
`

type UpdateUserRoleParams struct {
	ID   int32  `json:"id"`
	Role string `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRole, arg.ID, arg.Role)
	return err
}

const upsertPendingExtension = `-- name: UpsertPendingExtension :one
INSERT INTO extensions (key, display_name, version, menu_icon, menu_path, status, updated_at)
VALUES ($1, $2, $3, $4, $5, 'pending', NOW())
ON CONFLICT (key) DO UPDATE
    SET display_name = EXCLUDED.display_name,
        version      = EXCLUDED.version,
        menu_icon    = EXCLUDED.menu_icon,
        menu_path    = EXCLUDED.menu_path,
        updated_at   = NOW()
RETURNING key, display_name, version, menu_icon, menu_path, status, created_at, approved_at, updated_at
`

type UpsertPendingExtensionParams struct {
	Key         string `json:"key"`
	DisplayName string `json:"display_name"`
	Version     string `json:"version"`
	MenuIcon    string `json:"menu_icon"`
	MenuPath    string `json:"menu_path"`
}

func (q *Queries) UpsertPendingExtension(ctx context.Context, arg UpsertPendingExtensionParams) (Extension, error) {
	row := q.db.QueryRowContext(ctx, upsertPendingExtension,
		arg.Key,
		arg.DisplayName,
		arg.Version,
		arg.MenuIcon,
		arg.MenuPath,
	)
	var i Extension
	err := row.Scan(
		&i.Key,
		&i.DisplayName,
		&i.Version,
		&i.MenuIcon,
		&i.MenuPath,
		&i.Status,
		&i.CreatedAt,
		&i.ApprovedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyDownloadToken = `-- name: VerifyDownloadToken :one
SELECT file_id FROM file_download_tokens
WHERE token = $1 AND expires_at > NOW()
`

func (q *Queries) VerifyDownloadToken(ctx context.Context, token string) (string, error) {
	row := q.db.QueryRowContext(ctx, verifyDownloadToken, token)
	var file_id string
	err := row.Scan(&file_id)
	return file_id, err
}
