// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package sqlc

import (
	"context"
	"time"
)

const getExtensionVersion = `-- name: GetExtensionVersion :one
SELECT version FROM extension_versions WHERE extension_key = $1
`

func (q *Queries) GetExtensionVersion(ctx context.Context, extensionKey string) (string, error) {
	row := q.db.QueryRowContext(ctx, getExtensionVersion, extensionKey)
	var version string
	err := row.Scan(&version)
	return version, err
}

const getFile = `-- name: GetFile :one
SELECT id, filename, size, mime_type, storage_key, uploader_id, status, created_at FROM system_files WHERE id = $1
`

func (q *Queries) GetFile(ctx context.Context, id string) (SystemFile, error) {
	row := q.db.QueryRowContext(ctx, getFile, id)
	var i SystemFile
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Size,
		&i.MimeType,
		&i.StorageKey,
		&i.UploaderID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (user_id, action, extension_key, http_path, client_ip)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAuditLogParams struct {
	UserID       string `json:"user_id"`
	Action       string `json:"action"`
	ExtensionKey string `json:"extension_key"`
	HttpPath     string `json:"http_path"`
	ClientIp     string `json:"client_ip"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.UserID,
		arg.Action,
		arg.ExtensionKey,
		arg.HttpPath,
		arg.ClientIp,
	)
	return err
}

const insertDownloadToken = `-- name: InsertDownloadToken :exec
INSERT INTO file_download_tokens (token, file_id, user_id, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertDownloadTokenParams struct {
	Token     string    `json:"token"`
	FileID    string    `json:"file_id"`
	UserID    string    `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) InsertDownloadToken(ctx context.Context, arg InsertDownloadTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertDownloadToken,
		arg.Token,
		arg.FileID,
		arg.UserID,
		arg.ExpiresAt,
	)
	return err
}

const insertFile = `-- name: InsertFile :exec
INSERT INTO system_files (id, filename, size, mime_type, storage_key, uploader_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertFileParams struct {
	ID         string `json:"id"`
	Filename   string `json:"filename"`
	Size       int64  `json:"size"`
	MimeType   string `json:"mime_type"`
	StorageKey string `json:"storage_key"`
	UploaderID string `json:"uploader_id"`
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) error {
	_, err := q.db.ExecContext(ctx, insertFile,
		arg.ID,
		arg.Filename,
		arg.Size,
		arg.MimeType,
		arg.StorageKey,
		arg.UploaderID,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, user_id, action, extension_key, http_path, client_ip, created_at FROM audit_logs ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ExtensionKey,
			&i.HttpPath,
			&i.ClientIp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExtensionVersion = `-- name: UpdateExtensionVersion :exec
INSERT INTO extension_versions (extension_key, version, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (extension_key)
DO UPDATE SET version = EXCLUDED.version, updated_at = NOW()
`

type UpdateExtensionVersionParams struct {
	ExtensionKey string `json:"extension_key"`
	Version      string `json:"version"`
}

func (q *Queries) UpdateExtensionVersion(ctx context.Context, arg UpdateExtensionVersionParams) error {
	_, err := q.db.ExecContext(ctx, updateExtensionVersion, arg.ExtensionKey, arg.Version)
	return err
}

const verifyDownloadToken = `-- name: VerifyDownloadToken :one
SELECT file_id FROM file_download_tokens
WHERE token = $1 AND expires_at > NOW()
`

func (q *Queries) VerifyDownloadToken(ctx context.Context, token string) (string, error) {
	row := q.db.QueryRowContext(ctx, verifyDownloadToken, token)
	var file_id string
	err := row.Scan(&file_id)
	return file_id, err
}
