// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) error
	GetExtensionVersion(ctx context.Context, extensionKey string) (string, error)
	GetFile(ctx context.Context, id string) (SystemFile, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	InsertDownloadToken(ctx context.Context, arg InsertDownloadTokenParams) error
	InsertFile(ctx context.Context, arg InsertFileParams) error
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	UpdateExtensionVersion(ctx context.Context, arg UpdateExtensionVersionParams) error
	VerifyDownloadToken(ctx context.Context, token string) (string, error)
}

var _ Querier = (*Queries)(nil)
