// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.2
// source: proto/host.proto

// moduless.plugin.v1 host services: the Plugin -> Host contract.
//
// A plugin reaches these over a go-plugin GRPCBroker connection that Core
// hands it during Configure. Note there is no extension_key/tenant field
// anywhere below: Core serves a *separate* HostServices instance per plugin
// instance, with the key and granted permissions already closed over. Identity
// here is structural, not self-asserted, so a plugin cannot address another
// plugin's data by lying about who it is.

package plugin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HostServices_Put_FullMethodName                   = "/moduless.plugin.v1.HostServices/Put"
	HostServices_Get_FullMethodName                   = "/moduless.plugin.v1.HostServices/Get"
	HostServices_Delete_FullMethodName                = "/moduless.plugin.v1.HostServices/Delete"
	HostServices_Find_FullMethodName                  = "/moduless.plugin.v1.HostServices/Find"
	HostServices_Query_FullMethodName                 = "/moduless.plugin.v1.HostServices/Query"
	HostServices_Aggregate_FullMethodName             = "/moduless.plugin.v1.HostServices/Aggregate"
	HostServices_BatchWrite_FullMethodName            = "/moduless.plugin.v1.HostServices/BatchWrite"
	HostServices_BeginTx_FullMethodName               = "/moduless.plugin.v1.HostServices/BeginTx"
	HostServices_CommitTx_FullMethodName              = "/moduless.plugin.v1.HostServices/CommitTx"
	HostServices_RollbackTx_FullMethodName            = "/moduless.plugin.v1.HostServices/RollbackTx"
	HostServices_Enqueue_FullMethodName               = "/moduless.plugin.v1.HostServices/Enqueue"
	HostServices_Consume_FullMethodName               = "/moduless.plugin.v1.HostServices/Consume"
	HostServices_Ack_FullMethodName                   = "/moduless.plugin.v1.HostServices/Ack"
	HostServices_Nack_FullMethodName                  = "/moduless.plugin.v1.HostServices/Nack"
	HostServices_CacheGet_FullMethodName              = "/moduless.plugin.v1.HostServices/CacheGet"
	HostServices_CacheSet_FullMethodName              = "/moduless.plugin.v1.HostServices/CacheSet"
	HostServices_CacheDelete_FullMethodName           = "/moduless.plugin.v1.HostServices/CacheDelete"
	HostServices_AcquireLock_FullMethodName           = "/moduless.plugin.v1.HostServices/AcquireLock"
	HostServices_RenewLock_FullMethodName             = "/moduless.plugin.v1.HostServices/RenewLock"
	HostServices_ReleaseLock_FullMethodName           = "/moduless.plugin.v1.HostServices/ReleaseLock"
	HostServices_GetConfig_FullMethodName             = "/moduless.plugin.v1.HostServices/GetConfig"
	HostServices_PutFile_FullMethodName               = "/moduless.plugin.v1.HostServices/PutFile"
	HostServices_DeleteFile_FullMethodName            = "/moduless.plugin.v1.HostServices/DeleteFile"
	HostServices_GenerateDownloadToken_FullMethodName = "/moduless.plugin.v1.HostServices/GenerateDownloadToken"
	HostServices_GetFileMetadata_FullMethodName       = "/moduless.plugin.v1.HostServices/GetFileMetadata"
	HostServices_Fetch_FullMethodName                 = "/moduless.plugin.v1.HostServices/Fetch"
	HostServices_Publish_FullMethodName               = "/moduless.plugin.v1.HostServices/Publish"
	HostServices_Subscribe_FullMethodName             = "/moduless.plugin.v1.HostServices/Subscribe"
	HostServices_Log_FullMethodName                   = "/moduless.plugin.v1.HostServices/Log"
	HostServices_RecordMetric_FullMethodName          = "/moduless.plugin.v1.HostServices/RecordMetric"
)

// HostServicesClient is the client API for HostServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HostServicesClient interface {
	// --- Data (Core-Managed Document Store) ---------------------------------
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	Aggregate(ctx context.Context, in *AggregateRequest, opts ...grpc.CallOption) (*AggregateResponse, error)
	BatchWrite(ctx context.Context, in *BatchWriteRequest, opts ...grpc.CallOption) (*BatchWriteResponse, error)
	BeginTx(ctx context.Context, in *BeginTxRequest, opts ...grpc.CallOption) (*BeginTxResponse, error)
	CommitTx(ctx context.Context, in *TxRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RollbackTx(ctx context.Context, in *TxRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// --- Durable queue (PostgreSQL backed) ----------------------------------
	Enqueue(ctx context.Context, in *EnqueueRequest, opts ...grpc.CallOption) (*EnqueueResponse, error)
	Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueueMessage], error)
	Ack(ctx context.Context, in *AckRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Nack(ctx context.Context, in *NackRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// --- Cache and leases ----------------------------------------------------
	CacheGet(ctx context.Context, in *CacheGetRequest, opts ...grpc.CallOption) (*CacheGetResponse, error)
	CacheSet(ctx context.Context, in *CacheSetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CacheDelete(ctx context.Context, in *CacheDeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AcquireLock(ctx context.Context, in *AcquireLockRequest, opts ...grpc.CallOption) (*AcquireLockResponse, error)
	RenewLock(ctx context.Context, in *LeaseRequest, opts ...grpc.CallOption) (*AcquireLockResponse, error)
	ReleaseLock(ctx context.Context, in *LeaseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// --- Config --------------------------------------------------------------
	GetConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetConfigResponse, error)
	// --- Files ---------------------------------------------------------------
	PutFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutFileChunk, PutFileResponse], error)
	DeleteFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GenerateDownloadToken(ctx context.Context, in *DownloadTokenRequest, opts ...grpc.CallOption) (*DownloadTokenResponse, error)
	GetFileMetadata(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileMetadata, error)
	// --- Outbound HTTP (allow-listed, rate limited, audited by Core) ---------
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error)
	// --- Realtime event broadcast (best effort, in-memory) -------------------
	// For delivery that must not be lost, use the durable queue above instead.
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// --- Observability -------------------------------------------------------
	Log(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogRecord, emptypb.Empty], error)
	RecordMetric(ctx context.Context, in *MetricRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type hostServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewHostServicesClient(cc grpc.ClientConnInterface) HostServicesClient {
	return &hostServicesClient{cc}
}

func (c *hostServicesClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, HostServices_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, HostServices_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, HostServices_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindResponse)
	err := c.cc.Invoke(ctx, HostServices_Find_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, HostServices_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) Aggregate(ctx context.Context, in *AggregateRequest, opts ...grpc.CallOption) (*AggregateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AggregateResponse)
	err := c.cc.Invoke(ctx, HostServices_Aggregate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) BatchWrite(ctx context.Context, in *BatchWriteRequest, opts ...grpc.CallOption) (*BatchWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchWriteResponse)
	err := c.cc.Invoke(ctx, HostServices_BatchWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) BeginTx(ctx context.Context, in *BeginTxRequest, opts ...grpc.CallOption) (*BeginTxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginTxResponse)
	err := c.cc.Invoke(ctx, HostServices_BeginTx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) CommitTx(ctx context.Context, in *TxRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, HostServices_CommitTx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) RollbackTx(ctx context.Context, in *TxRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, HostServices_RollbackTx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) Enqueue(ctx context.Context, in *EnqueueRequest, opts ...grpc.CallOption) (*EnqueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnqueueResponse)
	err := c.cc.Invoke(ctx, HostServices_Enqueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueueMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HostServices_ServiceDesc.Streams[0], HostServices_Consume_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConsumeRequest, QueueMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostServices_ConsumeClient = grpc.ServerStreamingClient[QueueMessage]

func (c *hostServicesClient) Ack(ctx context.Context, in *AckRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, HostServices_Ack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) Nack(ctx context.Context, in *NackRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, HostServices_Nack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) CacheGet(ctx context.Context, in *CacheGetRequest, opts ...grpc.CallOption) (*CacheGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CacheGetResponse)
	err := c.cc.Invoke(ctx, HostServices_CacheGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) CacheSet(ctx context.Context, in *CacheSetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, HostServices_CacheSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) CacheDelete(ctx context.Context, in *CacheDeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, HostServices_CacheDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) AcquireLock(ctx context.Context, in *AcquireLockRequest, opts ...grpc.CallOption) (*AcquireLockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcquireLockResponse)
	err := c.cc.Invoke(ctx, HostServices_AcquireLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) RenewLock(ctx context.Context, in *LeaseRequest, opts ...grpc.CallOption) (*AcquireLockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcquireLockResponse)
	err := c.cc.Invoke(ctx, HostServices_RenewLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) ReleaseLock(ctx context.Context, in *LeaseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, HostServices_ReleaseLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) GetConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, HostServices_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) PutFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutFileChunk, PutFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HostServices_ServiceDesc.Streams[1], HostServices_PutFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PutFileChunk, PutFileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostServices_PutFileClient = grpc.ClientStreamingClient[PutFileChunk, PutFileResponse]

func (c *hostServicesClient) DeleteFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, HostServices_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) GenerateDownloadToken(ctx context.Context, in *DownloadTokenRequest, opts ...grpc.CallOption) (*DownloadTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadTokenResponse)
	err := c.cc.Invoke(ctx, HostServices_GenerateDownloadToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) GetFileMetadata(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileMetadata)
	err := c.cc.Invoke(ctx, HostServices_GetFileMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchResponse)
	err := c.cc.Invoke(ctx, HostServices_Fetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, HostServices_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HostServices_ServiceDesc.Streams[2], HostServices_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostServices_SubscribeClient = grpc.ServerStreamingClient[Event]

func (c *hostServicesClient) Log(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogRecord, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HostServices_ServiceDesc.Streams[3], HostServices_Log_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogRecord, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostServices_LogClient = grpc.ClientStreamingClient[LogRecord, emptypb.Empty]

func (c *hostServicesClient) RecordMetric(ctx context.Context, in *MetricRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, HostServices_RecordMetric_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostServicesServer is the server API for HostServices service.
// All implementations must embed UnimplementedHostServicesServer
// for forward compatibility.
type HostServicesServer interface {
	// --- Data (Core-Managed Document Store) ---------------------------------
	Put(context.Context, *PutRequest) (*PutResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	Find(context.Context, *FindRequest) (*FindResponse, error)
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	Aggregate(context.Context, *AggregateRequest) (*AggregateResponse, error)
	BatchWrite(context.Context, *BatchWriteRequest) (*BatchWriteResponse, error)
	BeginTx(context.Context, *BeginTxRequest) (*BeginTxResponse, error)
	CommitTx(context.Context, *TxRequest) (*emptypb.Empty, error)
	RollbackTx(context.Context, *TxRequest) (*emptypb.Empty, error)
	// --- Durable queue (PostgreSQL backed) ----------------------------------
	Enqueue(context.Context, *EnqueueRequest) (*EnqueueResponse, error)
	Consume(*ConsumeRequest, grpc.ServerStreamingServer[QueueMessage]) error
	Ack(context.Context, *AckRequest) (*emptypb.Empty, error)
	Nack(context.Context, *NackRequest) (*emptypb.Empty, error)
	// --- Cache and leases ----------------------------------------------------
	CacheGet(context.Context, *CacheGetRequest) (*CacheGetResponse, error)
	CacheSet(context.Context, *CacheSetRequest) (*emptypb.Empty, error)
	CacheDelete(context.Context, *CacheDeleteRequest) (*emptypb.Empty, error)
	AcquireLock(context.Context, *AcquireLockRequest) (*AcquireLockResponse, error)
	RenewLock(context.Context, *LeaseRequest) (*AcquireLockResponse, error)
	ReleaseLock(context.Context, *LeaseRequest) (*emptypb.Empty, error)
	// --- Config --------------------------------------------------------------
	GetConfig(context.Context, *emptypb.Empty) (*GetConfigResponse, error)
	// --- Files ---------------------------------------------------------------
	PutFile(grpc.ClientStreamingServer[PutFileChunk, PutFileResponse]) error
	DeleteFile(context.Context, *FileRequest) (*emptypb.Empty, error)
	GenerateDownloadToken(context.Context, *DownloadTokenRequest) (*DownloadTokenResponse, error)
	GetFileMetadata(context.Context, *FileRequest) (*FileMetadata, error)
	// --- Outbound HTTP (allow-listed, rate limited, audited by Core) ---------
	Fetch(context.Context, *FetchRequest) (*FetchResponse, error)
	// --- Realtime event broadcast (best effort, in-memory) -------------------
	// For delivery that must not be lost, use the durable queue above instead.
	Publish(context.Context, *PublishRequest) (*emptypb.Empty, error)
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Event]) error
	// --- Observability -------------------------------------------------------
	Log(grpc.ClientStreamingServer[LogRecord, emptypb.Empty]) error
	RecordMetric(context.Context, *MetricRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedHostServicesServer()
}

// UnimplementedHostServicesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostServicesServer struct{}

func (UnimplementedHostServicesServer) Put(context.Context, *PutRequest) (*PutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedHostServicesServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedHostServicesServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedHostServicesServer) Find(context.Context, *FindRequest) (*FindResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Find not implemented")
}
func (UnimplementedHostServicesServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedHostServicesServer) Aggregate(context.Context, *AggregateRequest) (*AggregateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Aggregate not implemented")
}
func (UnimplementedHostServicesServer) BatchWrite(context.Context, *BatchWriteRequest) (*BatchWriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchWrite not implemented")
}
func (UnimplementedHostServicesServer) BeginTx(context.Context, *BeginTxRequest) (*BeginTxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginTx not implemented")
}
func (UnimplementedHostServicesServer) CommitTx(context.Context, *TxRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitTx not implemented")
}
func (UnimplementedHostServicesServer) RollbackTx(context.Context, *TxRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackTx not implemented")
}
func (UnimplementedHostServicesServer) Enqueue(context.Context, *EnqueueRequest) (*EnqueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enqueue not implemented")
}
func (UnimplementedHostServicesServer) Consume(*ConsumeRequest, grpc.ServerStreamingServer[QueueMessage]) error {
	return status.Error(codes.Unimplemented, "method Consume not implemented")
}
func (UnimplementedHostServicesServer) Ack(context.Context, *AckRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Ack not implemented")
}
func (UnimplementedHostServicesServer) Nack(context.Context, *NackRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Nack not implemented")
}
func (UnimplementedHostServicesServer) CacheGet(context.Context, *CacheGetRequest) (*CacheGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CacheGet not implemented")
}
func (UnimplementedHostServicesServer) CacheSet(context.Context, *CacheSetRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CacheSet not implemented")
}
func (UnimplementedHostServicesServer) CacheDelete(context.Context, *CacheDeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CacheDelete not implemented")
}
func (UnimplementedHostServicesServer) AcquireLock(context.Context, *AcquireLockRequest) (*AcquireLockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcquireLock not implemented")
}
func (UnimplementedHostServicesServer) RenewLock(context.Context, *LeaseRequest) (*AcquireLockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewLock not implemented")
}
func (UnimplementedHostServicesServer) ReleaseLock(context.Context, *LeaseRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseLock not implemented")
}
func (UnimplementedHostServicesServer) GetConfig(context.Context, *emptypb.Empty) (*GetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedHostServicesServer) PutFile(grpc.ClientStreamingServer[PutFileChunk, PutFileResponse]) error {
	return status.Error(codes.Unimplemented, "method PutFile not implemented")
}
func (UnimplementedHostServicesServer) DeleteFile(context.Context, *FileRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedHostServicesServer) GenerateDownloadToken(context.Context, *DownloadTokenRequest) (*DownloadTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateDownloadToken not implemented")
}
func (UnimplementedHostServicesServer) GetFileMetadata(context.Context, *FileRequest) (*FileMetadata, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFileMetadata not implemented")
}
func (UnimplementedHostServicesServer) Fetch(context.Context, *FetchRequest) (*FetchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedHostServicesServer) Publish(context.Context, *PublishRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedHostServicesServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedHostServicesServer) Log(grpc.ClientStreamingServer[LogRecord, emptypb.Empty]) error {
	return status.Error(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedHostServicesServer) RecordMetric(context.Context, *MetricRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordMetric not implemented")
}
func (UnimplementedHostServicesServer) mustEmbedUnimplementedHostServicesServer() {}
func (UnimplementedHostServicesServer) testEmbeddedByValue()                      {}

// UnsafeHostServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostServicesServer will
// result in compilation errors.
type UnsafeHostServicesServer interface {
	mustEmbedUnimplementedHostServicesServer()
}

func RegisterHostServicesServer(s grpc.ServiceRegistrar, srv HostServicesServer) {
	// If the following call panics, it indicates UnimplementedHostServicesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostServices_ServiceDesc, srv)
}

func _HostServices_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_Find_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).Find(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_Aggregate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggregateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).Aggregate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_Aggregate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).Aggregate(ctx, req.(*AggregateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_BatchWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).BatchWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_BatchWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).BatchWrite(ctx, req.(*BatchWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_BeginTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).BeginTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_BeginTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).BeginTx(ctx, req.(*BeginTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_CommitTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).CommitTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_CommitTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).CommitTx(ctx, req.(*TxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_RollbackTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).RollbackTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_RollbackTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).RollbackTx(ctx, req.(*TxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_Enqueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).Enqueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_Enqueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).Enqueue(ctx, req.(*EnqueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_Consume_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConsumeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HostServicesServer).Consume(m, &grpc.GenericServerStream[ConsumeRequest, QueueMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostServices_ConsumeServer = grpc.ServerStreamingServer[QueueMessage]

func _HostServices_Ack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).Ack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_Ack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).Ack(ctx, req.(*AckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_Nack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).Nack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_Nack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).Nack(ctx, req.(*NackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_CacheGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).CacheGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_CacheGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).CacheGet(ctx, req.(*CacheGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_CacheSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).CacheSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_CacheSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).CacheSet(ctx, req.(*CacheSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_CacheDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).CacheDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_CacheDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).CacheDelete(ctx, req.(*CacheDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_AcquireLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcquireLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).AcquireLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_AcquireLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).AcquireLock(ctx, req.(*AcquireLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_RenewLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).RenewLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_RenewLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).RenewLock(ctx, req.(*LeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_ReleaseLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).ReleaseLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_ReleaseLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).ReleaseLock(ctx, req.(*LeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).GetConfig(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_PutFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HostServicesServer).PutFile(&grpc.GenericServerStream[PutFileChunk, PutFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostServices_PutFileServer = grpc.ClientStreamingServer[PutFileChunk, PutFileResponse]

func _HostServices_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).DeleteFile(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_GenerateDownloadToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).GenerateDownloadToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_GenerateDownloadToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).GenerateDownloadToken(ctx, req.(*DownloadTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_GetFileMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).GetFileMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_GetFileMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).GetFileMetadata(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_Fetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).Fetch(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HostServicesServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostServices_SubscribeServer = grpc.ServerStreamingServer[Event]

func _HostServices_Log_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HostServicesServer).Log(&grpc.GenericServerStream[LogRecord, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostServices_LogServer = grpc.ClientStreamingServer[LogRecord, emptypb.Empty]

func _HostServices_RecordMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).RecordMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_RecordMetric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).RecordMetric(ctx, req.(*MetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostServices_ServiceDesc is the grpc.ServiceDesc for HostServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "moduless.plugin.v1.HostServices",
	HandlerType: (*HostServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _HostServices_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _HostServices_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _HostServices_Delete_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _HostServices_Find_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _HostServices_Query_Handler,
		},
		{
			MethodName: "Aggregate",
			Handler:    _HostServices_Aggregate_Handler,
		},
		{
			MethodName: "BatchWrite",
			Handler:    _HostServices_BatchWrite_Handler,
		},
		{
			MethodName: "BeginTx",
			Handler:    _HostServices_BeginTx_Handler,
		},
		{
			MethodName: "CommitTx",
			Handler:    _HostServices_CommitTx_Handler,
		},
		{
			MethodName: "RollbackTx",
			Handler:    _HostServices_RollbackTx_Handler,
		},
		{
			MethodName: "Enqueue",
			Handler:    _HostServices_Enqueue_Handler,
		},
		{
			MethodName: "Ack",
			Handler:    _HostServices_Ack_Handler,
		},
		{
			MethodName: "Nack",
			Handler:    _HostServices_Nack_Handler,
		},
		{
			MethodName: "CacheGet",
			Handler:    _HostServices_CacheGet_Handler,
		},
		{
			MethodName: "CacheSet",
			Handler:    _HostServices_CacheSet_Handler,
		},
		{
			MethodName: "CacheDelete",
			Handler:    _HostServices_CacheDelete_Handler,
		},
		{
			MethodName: "AcquireLock",
			Handler:    _HostServices_AcquireLock_Handler,
		},
		{
			MethodName: "RenewLock",
			Handler:    _HostServices_RenewLock_Handler,
		},
		{
			MethodName: "ReleaseLock",
			Handler:    _HostServices_ReleaseLock_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _HostServices_GetConfig_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _HostServices_DeleteFile_Handler,
		},
		{
			MethodName: "GenerateDownloadToken",
			Handler:    _HostServices_GenerateDownloadToken_Handler,
		},
		{
			MethodName: "GetFileMetadata",
			Handler:    _HostServices_GetFileMetadata_Handler,
		},
		{
			MethodName: "Fetch",
			Handler:    _HostServices_Fetch_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _HostServices_Publish_Handler,
		},
		{
			MethodName: "RecordMetric",
			Handler:    _HostServices_RecordMetric_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Consume",
			Handler:       _HostServices_Consume_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PutFile",
			Handler:       _HostServices_PutFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _HostServices_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Log",
			Handler:       _HostServices_Log_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/host.proto",
}
